### ISSUE TITLE
error during model computing

### ISSUE THREAD

**Issue by razZ0r** [gstricker/fastGenoGAM#1]
Hi,

I just installed fastGenoGAM and trying to go through the "TL;DR analysis" from the vignette.

During the model computation I run into this error:

    > result <- genogam(ggd, lambda = 4601, theta = 4.51)
    INFO [2018-03-01 11:13:01] Initializing the model
    INFO [2018-03-01 11:13:01] Done
    INFO [2018-03-01 11:13:02] Fitting model
    
    error: matrix multiplication: incompatible matrix dimensions: 687194773760x164926745190400 and 4294967456x1
    Error: BiocParallel errors
        element index: 1, 2, 3
       first error: matrix multiplication: incompatible matrix dimensions: 687194773760x164926745190400 and 4294967456x1

If I remove the pre-set parameters:

    > result <- genogam(ggd)
    INFO [2018-03-01 11:14:38] Initializing the model
    INFO [2018-03-01 11:14:38] Done
    INFO [2018-03-01 11:14:39] Estimating hyperparameters
    Error in dimnames(x) <- dn : 
        length of 'dimnames' [2] not equal to array extent

Any suggestions on what might be going wrong here?

Endre

**Comment by gstricker** [comment]
Hi Endre,

I have stumbled across the first error myself once on my Linux Mint Debian Edition machine. The problem were some missing Linux libraries, such that the underlying C++ Armadillo library could not correctly represent the matrices. The OS dependent libraries for Armadillo are listed on their Sourceforge. But it is down at the moment. I'll post a link as soon as they are up again. The second error might be connected to it, I have not encountered it yet and can't reproduce it.

Best,

Georg

**Comment by razZ0r** [comment]
I [found some info](https://fossies.org/linux/armadillo/README.txt), and Armadillo on Linux (I have Ubuntu 16.04 LTS) seems to need OpenBLAS, LAPACK, SuperLU and ARPACK. I installed all of these and also the dev packages, reinstalled RcppArmadillo, but still getting the same error.

The description also says "only SuperLU version 5.2 can be used". Perhaps this is the problem? Which version is available on Linux Mint Debian?

**Comment by gstricker** [comment]
Hi Endre,
sorry for the late response, I was gone for a couple of days. The specific libraries I installed when I encountered this issue on LMDE were:  _cmake, libopenblas-dev, liblapack-dev, libarpack-dev_. However you seem to have covered that already. 
The SuperLU version shouldn't be the problem, since I'm not making use of it in the Armadillo code. I do use it however through the Matrix package, which is independent of the Armadillo code. Debian and Ubuntu anyway ship with libsuperlu4, as far as I can tell. 
The fastGenoGAM package is still very much in development and hasn't been tested sufficiently yet. For that reason I always use it with the current R-devel. Linux distributions I tested so far were ScientificLinux 7, Linux Mint 18,3 "Sylvia" and LMDE2 "Betsy". The first two worked out of the box, the last required the above mentioned packages.

Best,

Georg

**Comment by razZ0r** [comment]
Hi,

Thanks for the suggestions, I'll try with R-devel, or maybe reinstall the Matrix package. I know that the code is not stable and tested yet, but I'd really like to give it a try, as I have a new sequencing method and a few datasets (similar to ChIP-seq but not exactly ChIP-seq) where I think fastGenoGAM would be very useful. I'll let you know if I'm able to use the package.

Endre

**Comment by gstricker** [comment]
Hi Endre,

another source of problems with RcppArmadillo has been the default setting to 32bit instead of 64bit preventing large sparse matrices. I specifically define the 64bit mode in the code, but it does not seem to necessarily work in case of installation from GitHub. You can fix this by setting 

```
#define ARMA_64BIT_WORD 1
```

in [R root]/lib/R/library/RcppArmadillo/include/RcppArmadilloConfig.h

make sure its before the block:

```
#if !defined(ARMA_64BIT_WORD)
  #define ARMA_32BIT_WORD 1
#endif
```
I'm not sure it will help fixing your problem, but it might be worth trying.

Georg

**Comment by gstricker** [comment]
Hi Endre,

in case you are reading this. I could finally reproduce the error and found a solution I think. Do you mind installing and testing it again from GitHub?

Best,

Georg

**Comment by razZ0r** [comment]
Hi,

Thanks, I'll try asap! I did not have time for it in the last few days.

Endre

**Comment by razZ0r** [comment]
I finally managed to test the updated package (with R-3.5.0) and everything seems to be ok, the model computation finishes without errors. I have found other bugs, though.
