### ISSUE TITLE
no slot of name "filepath" ... error with hdf5 = TRUE

### ISSUE THREAD

**Issue by esebesty** [gstricker/fastGenoGAM#2]
Hi,

When running

```

ggd <- GenoGAMDataSet(
  expDesign, directory = folder,
  chunkSize = chunkSize, overhangSize = overhangSize,
  design = design,
  settings = settings, hdf5 = TRUE
)
```

and later

`result <- genogam(ggd, lambda = 4601, theta = 4.51)`

I get the error

`no slot of name "filepath" for this object of class "DelayedDimnames"`

If I set `hdf5 = FALSE` when creating the dataset, everything is ok.

Endre

**Comment by gstricker** [comment]
Hi Endre,

that is due to changes in the HDF5Array dependency, that should not appear if the new R and Bioconductor version is used (3.5 and 3.7 respectively). I updated the dependency versions accordingly, such that installation of fastGenoGAM should pull the correct packages (above all HDF5Array 1.8.0).

Best,

Georg
